### ISSUE TITLE
UpdateAudioDevices() throwing exceptions

### ISSUE THREAD

**Issue by rekyuu** [rekyuu/StanleyParableXiv#33]
```
---> System.InvalidCastException: Unable to cast object of type 'NAudio.CoreAudioApi.Interfaces.MMDeviceEnumeratorComObject' to type 'NAudio.CoreAudioApi.Interfaces.MMDeviceEnumeratorComObject'.
   at NAudio.CoreAudioApi.MMDeviceEnumerator..ctor()
   at StanleyParableXiv.Services.AudioService.UpdateAudioDevices() in /work/repo/StanleyParableXiv/Services/AudioService.cs:line 536
   at StanleyParableXiv.Services.AudioService..ctor() in /work/repo/StanleyParableXiv/Services/AudioService.cs:line 475
   at StanleyParableXiv.Services.AudioService..cctor() in /work/repo/StanleyParableXiv/Services/AudioService.cs:line 56
   --- End of inner exception stack trace ---
   at StanleyParableXiv.Events.DutyEvent.OnDutyStarted(Object sender, UInt16 e) in /work/repo/StanleyParableXiv/Events/DutyEvent.cs:line 78
   at Dalamud.Game.DutyState.DutyStatePluginScoped.DutyStartedForward(Object sender, UInt16 territoryId) in C:\goatsoft\companysecrets\dalamud\\Game\DutyState\DutyState.cs:line 214
   at Dalamud.Game.DutyState.DutyState.ContentDirectorNetworkMessageDetour(IntPtr a1, IntPtr a2, UInt16* a3) in C:\goatsoft\companysecrets\dalamud\\Game\DutyState\DutyState.cs:line 84
   at Dalamud.Game.Network.GameNetwork.ProcessZonePacketDownDetour(PacketDispatcher* dispatcher, UInt32 targetId, IntPtr dataPtr) in C:\goatsoft\companysecrets\dalamud\\Game\Network\GameNetwork.cs:line 97
   at Dalamud.Game.Framework.HandleFrameworkUpdate(Framework* thisPtr) in C:\goatsoft\companysecrets\dalamud\\Game\Framework.cs:line 472
```

**Comment by rekyuu** [comment]
Fixed by 3d1b1bbfcb1e87c2a71820455b7bc3ed1389d344
